# permissions to do viewer addons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: addon-viewer-role
rules:
- apiGroups:
  - discovery.addons.x-k8s.io
  resources:
  - addons
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - discovery.addons.x-k8s.io
  resources:
  - addons/status
  verbs:
  - get
